version: '3.3'
services:
  e-commerce-db:
    image: 'postgres:latest'
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: e_commerce_db
    restart: always
    networks:
      - workspace
    expose:
      - 5432

  e-commerce-api:
    build:
      dockerfile: Dockerfile
    container_name: api
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - workspace
    depends_on:
      - e-commerce-db

networks:
  workspace:
    driver: bridge